server:
  port: 8091

# 扳手通用组件配置
wl:
  wrench:
    config:
      system: prod-system
      register:
        host: ${REDIS_HOST:127.0.0.1}
        port: ${REDIS_PORT:6379}
        password: ${REDIS_PASSWORD:}

# 日志
logging:
  level:
    root: warn
  config: classpath:logback-spring.xml